# Generated by Django 3.1.5 on 2021-05-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_artist', models.CharField(db_index=True, max_length=200)),
                ('photo', models.ImageField(default='', upload_to='artist')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Avtor_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_avtor_text', models.CharField(db_index=True, max_length=200)),
                ('photo', models.ImageField(default='', upload_to='avtor')),
            ],
            options={
                'verbose_name': 'avtor_text',
                'verbose_name_plural': 'avtors_text',
            },
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_composer', models.CharField(db_index=True, max_length=200)),
                ('photo', models.ImageField(default='', upload_to='composer')),
            ],
            options={
                'verbose_name': 'composer',
                'verbose_name_plural': 'composers',
            },
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(db_index=True, max_length=200)),
                ('avt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.avtor_text')),
                ('comp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.composer')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, upload_to='audio/')),
                ('note', models.CharField(db_index=True, max_length=200)),
                ('artist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.artist')),
                ('song_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.song')),
            ],
            options={
                'verbose_name': 'execution',
                'verbose_name_plural': 'executions',
            },
        ),
    ]
