# Generated by Django 3.1.5 on 2021-05-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_translator', models.CharField(db_index=True, max_length=200)),
                ('fam_translator', models.CharField(db_index=True, default='', max_length=200)),
                ('photo', models.ImageField(default='', upload_to='translator')),
            ],
            options={
                'verbose_name': 'translator',
                'verbose_name_plural': 'translators',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='fam_artist',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='avtor_text',
            name='fam_avtor_text',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='composer',
            name='fam_composer',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='trans_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.translator'),
        ),
    ]
