# Generated by Django 3.1.5 on 2021-05-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210519_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='trans_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.translator'),
        ),
    ]
