# Generated by Django 3.1.5 on 2021-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210519_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workfield',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
