# Generated by Django 3.1.5 on 2021-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_execution_workfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workfield1',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
