# Generated by Django 3.1.5 on 2021-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_execution_workfield1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='workfield1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
