# Generated by Django 3.1.5 on 2021-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210522_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='workfield',
            field=models.CharField(blank=True, db_index=True, default=0, max_length=200),
        ),
    ]
