# Generated by Django 3.1.5 on 2021-05-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210524_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_composer', models.CharField(db_index=True, max_length=200)),
                ('fam_composer', models.CharField(db_index=True, default='', max_length=200)),
                ('photo', models.ImageField(default='', upload_to='composer')),
            ],
            options={
                'verbose_name': 'composer1',
                'verbose_name_plural': 'composer1s',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='comp1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.composer1'),
        ),
    ]
