# Generated by Django 3.1.5 on 2021-05-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210525_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='comp1_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.composer1'),
        ),
    ]
