# Generated by Django 3.1.5 on 2021-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210525_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workfield2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
