# Generated by Django 3.1.5 on 2021-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_execution_workfield2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_visit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cvisit',
                'verbose_name_plural': 'cvisits',
            },
        ),
    ]
