# Generated by Django 3.1.5 on 2021-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workfield3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
