# Generated by Django 3.1.5 on 2021-08-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
