# Generated by Django 3.1.5 on 2021-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210830_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='order',
            field=models.CharField(default='', max_length=3),
        ),
    ]
