# Generated by Django 3.1.5 on 2021-09-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_composer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composer',
            old_name='order',
            new_name='orderr',
        ),
    ]
