# Generated by Django 3.1.5 on 2021-09-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210902_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='background_ph',
            field=models.ImageField(default='', upload_to='composer'),
        ),
    ]
