# Generated by Django 3.1.5 on 2021-09-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_composer_background_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer1',
            name='fon',
            field=models.ImageField(default='', upload_to='composer'),
        ),
    ]
