# Generated by Django 3.1.5 on 2021-09-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_composer1_fon'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='sco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
