# Generated by Django 3.1.5 on 2021-09-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_composer_sco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='background_ph',
            field=models.ImageField(blank=True, default='', null=True, upload_to='composer'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='orderr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
