# Generated by Django 3.1.5 on 2021-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210929_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='sco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
