# Generated by Django 3.1.5 on 2021-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_artist_sco'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='sco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
