# Generated by Django 3.1.5 on 2021-09-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_execution_sco'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer1',
            name='fon1',
            field=models.ImageField(default='', upload_to='composer'),
        ),
    ]
