# Generated by Django 3.1.5 on 2021-10-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_composer1_fon1'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='vid',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
