# Generated by Django 3.1.5 on 2021-11-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_execution_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='note1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
